### ISSUE TITLE
how to control the backend part in wordpress ?

### ISSUE THREAD

**Issue by TimelyResponse** [TimelyResponse/php-WP-backend-react#3]
please answer.

**Comment by matsudaWWW** [comment]
You can use a plugin like Yoast SEO or All-in-One WP SEO which will allow you to set meta descriptions, titles and keywords for each page on your website. These plugins also provide other features such as link building tools, content optimization suggestions and more. 2. If you want to do it manually then you need to edit the theme files and add the necessary code. For example if you are using Twenty Seventeen theme then go to functions.php file and find this line of code: separator = ' &middot; '; // The separator between blog title and site name. Then change that to something else like separator = '-'; This way all links generated by WordPress will have dashes instead of dots.

**Comment by TimelyResponse** [comment]
Yes,  Thanks.
in my opinion, the best way is following as.

Using an SEO plugin is a common approach. Plugins like Yoast SEO and All In One SEO are popular as they allow easy meta tag editing and link analysis per page.
Direct theme file editing is also possible, but depends on the specific theme. For example, in Twenty Seventeen the title separator can be changed in functions.php.
Additionally, metadata code could be added to individual templates like header.php or using filters like wp_title.

**Comment by matsudaWWW** [comment]
Ok
great

**Comment by TimelyResponse** [comment]
thanks.

**Comment by matsudaWWW** [comment]
awesome
